name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram notification
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d parse_mode="Markdown" \
            -d text="🚀 Deployment starting by *${{ github.actor }}* on *${{ github.ref_name }}*"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }} 
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          script: |
            echo "Starting deployment..."
            cd /var/www/test-next-ci
            echo "Pulling latest code..."
             git pull origin main
            echo "Installing dependencies..."
             npm install  # Make sure dependencies are installed
            echo "Building app..."
              npm run build
            
            # Check if app is running with PM2
            if sudo pm2 list | grep -q "green"; then
              echo "App is already running, restarting with PM2..."
               pm2 restart green  # Restart the PM2 process
            else
              echo "App not running, starting with PM2..."
              pm2 start npm --name "test-v1" -- run start  # Start with PM2
            fi
            
            echo "Deployment complete."
      
       # Send post-deployment Telegram notification
      - name: Send post-deployment Telegram notification
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d parse_mode="Markdown" \
            -d text="✅ *Deployment complete* for *${{ github.ref_name }}* by *${{ github.actor }}*.\n\n[View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
       