name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Next.js app
        run: npm run build

      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }} 
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          script: |
            echo "Starting deployment..."
            cd /var/www/test-next-ci
            echo "Pulling latest code..."
            git pull
            echo "Installing dependencies..."
            npm install  # Make sure dependencies are installed
            echo "Building app..."
            npm run build
            
            # Check if app is running with PM2
            if pm2 list | grep -q "your-app-name"; then
              echo "App is already running, restarting with PM2..."
              pm2 restart your-app-name  # Restart the PM2 process
            else
              echo "App not running, starting with PM2..."
              pm2 start npm --name "your-app-name" -- run start  # Start with PM2
            fi
            
            echo "Deployment complete."
